version: '3'

services:
  app:
    image: my-server
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=YOUR_APP_KEY

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=zl_sneaker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=